config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :tasks
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project


  enum status: { high: 2, medium: 1, low: 0 }

  default_scope { order ('completed ASC, tasks.status DESC') }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task = Task.new
    @tasks = @project.tasks
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end
  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  def edit
    @task = Task.find_by(id: params[:id])
  end

  def create
    @task = Task.create(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@task.project_id), notice: 'Task was successfully saved.' }
        format.json { render :show, status: :ok, location: @task  }
      else
        redirect_to root_path
      end
    end

  end

  #PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task = Task.find_by(id: params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_path(@task.project_id), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task  }
      else
        redirect_to root_path
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    task = Task.find_by(id: params[:id])
    project = Project.find_by(id: task.project_id)
    task.destroy
    respond_to do |format|
      format.html { redirect_to project_path(project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :status, :completed, :deadline, :project_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_avatar(user, size=40)
     if user.avatar.attached?
        user.avatar.variant(resize: "#{size}x#{size}!")
     else
          gravatar_image_url(user.email, size: size)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="card mb-4 mt-4  bg-light mx-auto" style="max-width: 600px;">

    <div class="row mb-4 mt-4 text-center text-info">
      <div class="col ml-4 mr-3">

        <% if user_signed_in? %>
          <div>To continue work please press the button </div>
          <div class="btn">
            <%= link_to 'Continue', projects_path, class: "btn btn-lg btn-outline-info" %>
          </div>

        <% else %>
          <h2>Please pass authentication to be able to create and view projects and tasks!</h2>

          <div class="btn">
            <%= link_to 'Sing up', new_user_registration_path, class: "btn btn-lg btn-outline-info" %>
          </div>

          <div class="btn">
            <%= link_to 'Sing in', new_user_session_path, class: "btn btn-lg btn-outline-info" %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <div class="container">
    <body>
      <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </body>
  </div>

</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_form_add_task.html.erb
<%= form_for @task do |form| %>

  <div class="form-row align-items-center">

    <%= form.hidden_field :project_id, value: @project.id %>

    <div class="col-10">

      <%= form.text_field :name, class: "form-control mr-2 sr-only-focusable", placeholder: "Start typing here to create a task...", required: true %>

    </div>

    <div class="col-2">

      <%= form.submit "Add Task", class: "btn btn-success my-2 sr-only-focusable" %>

    </div>

<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="bp-card mb-5 mx-auto" style="max-width: 700px;">

    <div class="card-body bg-light">
      <h1 class="card-title text-center text-primary">Editing Project</h1>

      <%= render 'form', project: @project %>

      <br>
      <%= link_to 'Show Project Details', @project, class: "btn btn-sm btn-outline-info" %>
      <%= link_to 'Back', projects_path, class: "btn btn-sm btn-outline-info" %>

    </div>

  </div>
</div>

app/views/projects/index.html.erb
  <% @projects.each do |project| %>
    <% if project.user == current_user %>

      <div class="container">
        <div class="card mb-4 mt-4  bg-light mx-auto" style="max-width: 700px;">
          <div class="row mb-4 mt-4">
             <div class="col ml-4"><%= project.name %></div>
             <div class="col text-right mr-2"><%= link_to 'Show Details snd Tasks', project , class: "btn btn-sm btn-outline-success" %>
             <%= link_to 'Edit', edit_project_path(project), class: "btn btn-sm btn-outline-info" %>
             <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %></div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
      <div class="card mb-4 mt-4 bg-light mx-auto" style="max-width: 700px;">
        <%= link_to 'Add New Project', new_project_path, class: "btn btn-sm btn-outline-info"  %>
      </div>

app/views/projects/new.html.erb
<div class="container">
  <div class="bp-card mb-5 mx-auto" style="max-width: 700px;">
    <div class="card-body bg-light">
      <h1 class="card-title text-center text-primary">New Project</h1>

      <%= render 'form', project: @project %>

      <br>
      <%= link_to 'Back', projects_path, class: "btn btn-sm btn-outline-info" %>

    </div>

  </div>

app/views/projects/show.html.erb
<p class="text-success" id="notice"><%= notice %></p>

<div class="container">
  <div class="bp-card mb-5 mx-auto">

    <div class="card-header">

      Project name: <%= @project.name %>

       <%= render 'projects/form_add_task' %>
    </div>

      <table class="table table-bordered mt-4">
        <tbody>
        <% @tasks.each do |task| %>
          <% if task.completed %>
            <tr class="table-secondary d-flex">
              <td class="col-1">Done</td>
              <td class="col-2 striker">Deadline <%= task.deadline %></td>
              <td class="col-6 striker"><%=  task.name %></td>
              <td class="col-3">
                <%= task.status %>
                <%= link_to 'Edit', edit_task_path(task), class: "btn btn-sm btn-outline-info" %>
                <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
              </td>
          <% else %>
            <tr class="d-flex">
              <td class="col-1"> In work </td>
              <td class="col-2">Deadline <%= task.deadline %></td>
              <td class="col-6"><%= task.name %></td>
              <td class="col-3">
                <%= task.status %>
                <%= link_to 'Edit', edit_task_path(task), class: "btn btn-sm btn-outline-info" %>
                <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
              </td>
          <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <br>

        <p><%= link_to 'Back', projects_path, class: "btn btn-sm btn-outline-info" %></p>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <a> <%= link_to 'SIMPLE TODO LIST', root_path, class: "navbar-brand text-white" %> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">

       <% if user_signed_in? %>
        <li class="nav-link text-white">
          <%=  current_user.email %>
        </li>

        <li class="nav-link">
          <%= image_tag user_avatar(current_user, 20), class: "rounded-circle" %>
        </li>

        <li class="nav-item">
          <%=  link_to 'Edit Profile', edit_user_registration_path,  class: "nav-link text-white" %>
        </li>

        <li class="nav-item">
          <%=  link_to 'Sing out', destroy_user_session_path, method: :delete, class: "nav-link text-white" %>
        </li>

      <% else %>
        <li class="nav-item">
        <%= link_to 'Sing up', new_user_registration_path, class: "nav-link text-white" %>
        </li>

        <li class="nav-item">
        <%= link_to 'Sing in', new_user_session_path, class: "nav-link text-white" %>
        </li>

      <% end %>
    </ul>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, value: task.name %>
  </div>
  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys.to_a %>
  </div>
  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>
  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_field :deadline %>
  </div>

  <div class="action">
    <%= form.submit%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="bp-card mb-5 mx-auto bg-light" style="max-width: 700px;">
    <div class="card-body bg-light">
      <h1 class="card-title text-center text-primary">Editing Task</h1>

      <%= render 'tasks/form', task: @task %>

      <br>

      <%= link_to 'Back', project_path(@task.project_id), class: "btn btn-sm btn-outline-info" %>

    </div>
  </div>
</div>